name: OSSF Scorecard

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        persist-credentials: false
    - uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
    - uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
      with:
        sarif_file: results.sarif
