# This GitHub action is designed to update the JSON data inside this repository

name: Update Temurin JSON

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # to push local changes (gr2m/create-or-update-pull-request-action)
  pull-requests: write  # to create a PR (gr2m/create-or-update-pull-request-action)

jobs:
  update:
    if: github.repository_owner == 'adoptium'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          repository: adoptium/marketplace-api.adoptium.net
          ref: production
          path: api
          submodules: true
          persist-credentials: false

      - name: Build Marketplace
        uses: ./api/.github/actions/build-marketplace
        with:
          RUN_TESTS: false
          WORKING_DIRECTORY: api

      - name: Generate JSON data
        env:
          KEY: ${{ secrets.TEMURIN_RSA_PRIVATE }}
        run: ../mvnw test -Dtest=ExtractAdoptiumReleases
        working-directory: api/adoptium-marketplace-utils
        
      - name: Copy output JSON and .sign files before copying updated versions
        run: |
          # Remove all existing JSON and signature files + api repo
          rm -r **/*.json **/*.sign api
          cp -R /tmp/adoptiumRepo/* .

      - name: Check to see if JSON files have changed or not
        run: |
          DIFF=$(git status | egrep ".*\.json$" | wc -l | tr -d '[:space:]')
          echo "DIFF=$DIFF" >> $GITHUB_OUTPUT
          if [[ $DIFF != "0" ]]; then
            FULL_DIFF=$(git status | egrep ".*\.json$")
            for file in **/*.sign; do
              JSON_PATH=$(echo $file | sed -e "s/.sha256.sign//")
              EXISTS=$(git ls-tree -r origin/main -- $file)
              if [[ -z "$EXISTS" ]]; then 
                echo "Add new file: $file"
              else
                if [ ! -n "$(echo "$FULL_DIFF" | grep "$JSON_PATH")" ]; then
                  git checkout main "$file"
                fi
              fi
            done
          fi
        id: diff

      - uses: gr2m/create-or-update-pull-request-action@77596e3166f328b24613f7082ab30bf2d93079d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
        if: steps.diff.outputs.DIFF != 0
        with:
          title: "Update Temurin JSON data"
          body: "This is an automatically generated pull request, it will be automatically merged."
          branch: "updater"
          commit-message: "updater: automated json updates"
          labels: automerge
          author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          repository: adoptium/marketplace-api.adoptium.net
          ref: production
          path: api
          submodules: true
          persist-credentials: false
