name: Validate Temurin JSON

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-adoptium-verifier:
    uses: ./.github/workflows/validate-data.yml
    with:
      signature-type: BASE64_ENCODED
      public-key: ${{ secrets.TEMURIN_RSA_PRIVATE }}
