# This GitHub action is designed to update the JSON data inside this repository

name: Update Temurin JSON

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    if: github.repository_owner == 'adoptium'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: adoptium/api.adoptium.net
          ref: marketplace
          path: api
          persist-credentials: false

      - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
        
      - name: Build API
        run: ./mvnw -DskipTests --batch-mode clean install -Padoptium
        working-directory: api
        
      - name: Build Marketplace
        run: ../mvnw -DskipTests --batch-mode clean install
        working-directory: api/marketplace
        
      - name: Generate JSON data
        env:
          KEY: ${{ secrets.TEMURIN_RSA_PRIVATE }}
        run: ../../mvnw test -Dtest=ExtractAdoptiumReleases
        working-directory: api/marketplace/adoptium-marketplace-utils
        
      - name: Copy output JSON and .sign files before copying updated versions
        run: |
          # Remove all existing JSON and signature files + api repo
          rm -r **/*.json **/*.sign api
          cp -R /tmp/adoptiumRepo/* .

      - name: Check to see if JSON files have changed or not
        run: |
          DIFF=$(git status | egrep ".*\.json$" | wc -l | tr -d '[:space:]')
          echo "::set-output name=DIFF::$DIFF"
          if [[ $DIFF != "0" ]]; then
            FULL_DIFF=$(git status | egrep ".*\.json$")
            for file in **/*.sign; do
              JSON_PATH=$(echo $file | sed -e "s/.sha256.sign//")
              if [ ! -n "$(echo "$FULL_DIFF" | grep "$JSON_PATH")" ]; then
                git checkout main "$file"
              fi
            done
          fi
        id: diff

      - uses: gr2m/create-or-update-pull-request-action@77596e3166f328b24613f7082ab30bf2d93079d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
        if: steps.diff.outputs.DIFF != 0
        with:
          title: "Update Temurin JSON data"
          body: "This is an automatically generated pull request, it will be automatically merged."
          branch: "updater"
          commit-message: "updater: automated json updates"
          labels: automerge
          author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"
