# This GitHub action is designed to update the JSON data inside this repository

name: Validate Marketplace JSON

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      public-key:
        required: true
        type: string
      signature-type:
        required: true
        type: string
      json-path:
        required: false
        type: string

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: adoptium/api.adoptium.net
          ref: marketplace
          path: api
          persist-credentials: false

      - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build API
        run: ./mvnw -DskipTests --batch-mode clean install -Padoptium
        working-directory: api

      - name: Build Marketplace
        run: ../mvnw -DskipTests --batch-mode clean install
        working-directory: api/marketplace

      - name: Validate data
        env:
          ALLOW_FILE_BASED_URL: true
          REPO_SIGNATURE_TYPE: ${{ inputs.signature-type }}
          REPO_URL: file://${{ github.workspace }}/${{ inputs.json-path }}
          REPO_KEY: ${{ inputs.public-key }}
        run: ../../mvnw --batch-mode clean test
        working-directory: api/marketplace/adoptium-marketplace-vendor-validation
