# This GitHub action is designed to update the JSON data inside this repository

name: Validate Marketplace JSON

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      public-key:
        required: true
        type: string
      signature-type:
        required: true
        type: string
      json-path:
        required: false
        type: string

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: adoptium/api.adoptium.net
          ref: marketplace
          path: api
          persist-credentials: false

      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build API
        run: ./mvnw -DskipTests --batch-mode clean install -Padoptium
        working-directory: api

      - name: Build Marketplace
        run: ../mvnw -DskipTests --batch-mode clean install
        working-directory: api/marketplace

      - name: Validate data
        env:
          ALLOW_FILE_BASED_URL: true
          REPO_SIGNATURE_TYPE: ${{ inputs.signature-type }}
          REPO_URL: file://${{ github.workspace }}/${{ inputs.json-path }}
          REPO_KEY: ${{ inputs.public-key }}
        run: ../../mvnw --batch-mode clean test
        working-directory: api/marketplace/adoptium-marketplace-vendor-validation

  download-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 2

      # get list of changed files
      - name: Get list of changed files
        id: changed-files
        run: |
          changed_files=$(git diff --diff-filter=AMR --name-only -r HEAD~1 HEAD)
          # filter out all non json files
          json_files=$(echo "$changed_files" | grep -E "\.json$" || true)
          echo "files=$json_files" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        if: steps.changed-files.outputs.files != ''
        with:
          python-version: '3.11'

      # checkout adoptium/marketplace-data to get the download-testing.py script
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        if: github.repository_owner != 'adoptium' && steps.changed-files.outputs.files != ''
        with:
          repository: adoptium/marketplace-data
          ref: main
          path: adoptium
          persist-credentials: false
      
      - name: Set working directory
        if: steps.changed-files.outputs.files != ''
        run: |
          if ${{ github.repository_owner == 'adoptium' }}; then
            echo "workdir=.github/workflows" >> $GITHUB_ENV
          else
            echo "workdir=adoptium/.github/workflows" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        if: steps.changed-files.outputs.files != ''
        run: pip install -r requirements.txt
        working-directory: ${{ env.workdir }}

      - name: Download testing
        if: steps.changed-files.outputs.files != ''
        run: |
          # loop through changed files
          for file in $(echo ${{ steps.changed-files.outputs.files }} | tr " " "\n"); do
            python ${{ env.workdir }}/download-testing.py "${file}"
          done
