# This GitHub action is designed to update the JSON data inside this repository

name: Validate Marketplace JSON

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      public-key:
        required: true
        type: string
      signature-type:
        required: true
        type: string
      json-path:
        required: false
        type: string

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: adoptium/marketplace-api.adoptium.net
          ref: production
          path: api
          submodules: true
          persist-credentials: false

      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build API
        run: ./mvnw -DskipTests --batch-mode clean install -Padoptium
        working-directory: api/api.adoptium.net

      - name: Build Marketplace
        run: ./mvnw -DskipTests --batch-mode clean install
        working-directory: api

      - name: Validate data
        env:
          ALLOW_FILE_BASED_URL: true
          REPO_SIGNATURE_TYPE: ${{ inputs.signature-type }}
          REPO_URL: file://${{ github.workspace }}/${{ inputs.json-path }}
          REPO_KEY: ${{ inputs.public-key }}
        run: ../mvnw --batch-mode clean test
        working-directory: api/adoptium-marketplace-vendor-validation
